### ISSUE TITLE
Mode change is broken in commands

### ISSUE THREAD

**Issue by Tranquility** [alexgenco/neovim-ruby#8] opened 2016-03-14 21:43 UTC
I realized that changing into insert mode does not really work.
Inside of a command the following snipped requires another key press before it switches to insert mode however in functions it's working fine.

```ruby
nvim.command("startinsert")
```

**Comment by justinmk** [comment] 2016-03-14 22:07
`:startinsert`/`:stopinsert` are documented rather specifically: they do not take effect until the current "script" or mapping is complete. 

> requires another key press before it switches to insert mode 

If you `eval()` an empty string, does it work as well?

**Comment by Tranquility** [comment] 2016-03-14 22:29
@justinmk thanks for your help.

> If you eval() an empty string, does it work as well?

No, but I don't think it's a neovim issue because I tested it with the python module and it works.  Also wouldn't functions have the same problem?

**Comment by justinmk** [comment] 2016-03-14 22:35
> Also wouldn't functions have the same problem?

Not sure. I haven't studied the codepath of `vim_command` but it has some quirks that I have encountered when writing tests.

**Comment by Tranquility** [comment] 2016-03-14 22:49
I also experienced problems with other commands that operate in insert mode, just used `:startinsert` to make it easily reproducible.

For now I am defining the functions in ruby and commands that call them in vimscript as a workaround.

**Comment by alexgenco** [comment] 2016-03-14 23:34
@Tranquility just reproduced. I'll look into it later tonight.

**Comment by alexgenco** [comment] 2016-03-15 02:45
I get the same result when interacting directly via a non-Ruby msgpack client (this is [msgpack-lite](https://www.npmjs.com/package/msgpack-lite)):

```shell
echo '[0, 0, "vim_command", ["startinsert"]]' | msgpack -Jm | nc -U /tmp/nvim.sock | msgpack -jM
```

Takes a keystroke before actually entering insert mode. @Tranquility do you get the same?

**Comment by alexgenco** [comment] 2016-05-20 05:40
Closing this for now since I'm not sure anything can be done here.

**Closed by alexgenco** 2016-05-20 05:40 UTC
